### ISSUE TITLE
No module named 'inference.PIPNet.FaceBoxesV2.utils.nms.cpu_nms'

### ISSUE THREAD

**Issue by arnold408** [ygtxr1997/ReliableSwap#10]
[root@www inference]# bash ./faceshifter_infer.sh
demo0: faceshifter vanilla, image infer
Traceback (most recent call last):
  File "/root/ReliableSwap/inference/faceshifter_infer.py", line 27, in <module>
    from PIPNet.lib.tools import get_lmk_model, demo_image
  File "/root/ReliableSwap/inference/PIPNet/lib/tools.py", line 6, in <module>
    from inference.PIPNet.FaceBoxesV2.faceboxes_detector import *
  File "/root/ReliableSwap/inference/../inference/PIPNet/FaceBoxesV2/faceboxes_detector.py", line 8, in <module>
    from inference.PIPNet.FaceBoxesV2.utils.nms_wrapper import nms
  File "/root/ReliableSwap/inference/../inference/PIPNet/FaceBoxesV2/utils/nms_wrapper.py", line 8, in <module>
    from .nms.cpu_nms import cpu_nms, cpu_soft_nms
ModuleNotFoundError: No module named 'inference.PIPNet.FaceBoxesV2.utils.nms.cpu_nms'

**Comment by xiuyuan0216** [comment]
That file is a pyx file. pyx file needs to compile before you import the file. There is a make.sh in upper directory and you need to run the script first.
